// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceIEDUCA.Data;

#nullable disable

namespace ServiceIEDUCA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315233430_AddNotificacoesEAtividadeQuestoes")]
    partial class AddNotificacoesEAtividadeQuestoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceIEDUCA.Models.AtividadeAtribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EscolaId")
                        .HasColumnType("integer");

                    b.Property<string>("Instrucoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Ativa");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("EscolaId");

                    b.HasIndex("AlunoId", "Status")
                        .HasDatabaseName("IX_AtividadeAtribuicoes_AlunoId_Status");

                    b.HasIndex("ProfessorId", "EscolaId")
                        .HasDatabaseName("IX_AtividadeAtribuicoes_ProfessorId_EscolaId");

                    b.ToTable("AtividadeAtribuicoes");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.AtividadeExecucoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acertos")
                        .HasColumnType("integer");

                    b.Property<string>("Ano")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conteudo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Erros")
                        .HasColumnType("integer");

                    b.Property<string>("GabaritoJson")
                        .HasColumnType("text");

                    b.Property<bool>("GeradaPorIA")
                        .HasColumnType("boolean");

                    b.Property<string>("Materia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("QuestoesJson")
                        .HasColumnType("text");

                    b.Property<string>("RespostasJson")
                        .HasColumnType("text");

                    b.Property<string>("Segmento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Em Andamento");

                    b.Property<int?>("TempoGastoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalQuestoes")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId")
                        .HasDatabaseName("IX_AtividadeExecucoes_AtividadeId");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("IX_AtividadeExecucoes_CriadoEm");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AtividadeExecucoes_Status");

                    b.HasIndex("UserId", "CriadoEm")
                        .HasDatabaseName("IX_AtividadeExecucoes_UserId_CriadoEm");

                    b.ToTable("AtividadeExecucoes");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.AtividadeQuestaoResultados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ExecucaoId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroQuestao")
                        .HasColumnType("integer");

                    b.Property<string>("RespostaAluno")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RespostaCorreta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("TempoGastoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("TopicoEspecifico")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Resultado")
                        .HasDatabaseName("IX_AtividadeQuestaoResultados_Resultado");

                    b.HasIndex("ExecucaoId", "NumeroQuestao")
                        .HasDatabaseName("IX_AtividadeQuestaoResultados_ExecucaoId_NumeroQuestao");

                    b.ToTable("AtividadeQuestaoResultados");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Atividades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExplicacoesJson")
                        .HasColumnType("text");

                    b.Property<string>("GabaritoJson")
                        .HasColumnType("text");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<string>("NivelDificuldade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QuestoesJson")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalQuestoes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Conhecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("areas_conhecimento");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Escola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("data_criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("escola");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Materias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("area_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("materias");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Lida")
                        .HasDatabaseName("IX_Notificacoes_UserId_Lida");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.ProfessorCompetenciaRevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioProfessor")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("NotaProfessor")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCompetencia")
                        .HasColumnType("integer");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId", "NumeroCompetencia")
                        .IsUnique()
                        .HasDatabaseName("IX_ProfessorCompetenciaRevisoes_RevisaoId_Numero");

                    b.ToTable("ProfessorCompetenciaRevisoes");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.ProfessorRedacaoGrifo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("yellow");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PosicaoFim")
                        .HasColumnType("integer");

                    b.Property<int>("PosicaoInicio")
                        .HasColumnType("integer");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId")
                        .HasDatabaseName("IX_ProfessorRedacaoGrifos_RevisaoId");

                    b.ToTable("ProfessorRedacaoGrifos");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.ProfessorRedacaoRevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComentarioGeral")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("NotaTotalProfessor")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("RedacaoCorrecaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("IX_ProfessorRedacaoRevisoes_ProfessorId");

                    b.HasIndex("RedacaoCorrecaoId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProfessorRedacaoRevisoes_RedacaoCorrecaoId");

                    b.ToTable("ProfessorRedacaoRevisoes");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoCompetencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidencias")
                        .HasColumnType("text");

                    b.Property<string>("Melhorias")
                        .HasColumnType("text");

                    b.Property<string>("NomeCompetencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCompetencia")
                        .HasColumnType("integer");

                    b.Property<int>("RedacaoCorrecaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RedacaoCorrecaoId");

                    b.ToTable("RedacaoCompetencias");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoCorrecoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtividadeExecucaoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ConfiancaAvaliacao")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoNotaZero")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NotaTotal")
                        .HasColumnType("int");

                    b.Property<bool>("NotaZero")
                        .HasColumnType("boolean");

                    b.Property<int>("Progresso")
                        .HasColumnType("integer");

                    b.Property<string>("ResumoFinal")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TextoRedacao")
                        .HasColumnType("text");

                    b.Property<string>("TipoAvaliacao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VersaoReescrita")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeExecucaoId");

                    b.HasIndex("UserId");

                    b.ToTable("RedacaoCorrecoes");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoCustos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustoOut")
                        .HasColumnType("integer");

                    b.Property<decimal>("CustoOutPricing")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("FkRedacao")
                        .HasColumnType("integer");

                    b.Property<decimal>("PromptCacheHitPricing")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("PromptCacheHitTokens")
                        .HasColumnType("integer");

                    b.Property<decimal>("PromptCacheMissPricing")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("PromptCacheMissTokens")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("FkRedacao")
                        .IsUnique()
                        .HasDatabaseName("IX_RedacaoCustos_FkRedacao");

                    b.ToTable("RedacaoCustos");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoErrosGramaticais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explicacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PosicaoFim")
                        .HasColumnType("integer");

                    b.Property<int>("PosicaoInicio")
                        .HasColumnType("integer");

                    b.Property<int>("RedacaoCorrecaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Severidade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TextoOriginal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TextoSugerido")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RedacaoCorrecaoId");

                    b.ToTable("RedacaoErrosGramaticais");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoFeedbacks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("RedacaoCorrecaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RedacaoCorrecaoId");

                    b.ToTable("RedacaoFeedbacks");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoPropostaIntervencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avaliacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RedacaoCorrecaoId")
                        .HasColumnType("integer");

                    b.Property<string>("SugestoesConcretas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RedacaoCorrecaoId")
                        .IsUnique();

                    b.ToTable("RedacaoPropostaIntervencao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("id_Escola")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_Escola");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.AtividadeAtribuicao", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.User", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");

                    b.HasOne("ServiceIEDUCA.Models.Atividades", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceIEDUCA.Models.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceIEDUCA.Models.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Atividade");

                    b.Navigation("Escola");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.AtividadeExecucoes", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.Atividades", "Atividade")
                        .WithMany("Execucoes")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.AtividadeQuestaoResultados", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.AtividadeExecucoes", "Execucao")
                        .WithMany("QuestaoResultados")
                        .HasForeignKey("ExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execucao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Atividades", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.Materias", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Notificacao", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.ProfessorCompetenciaRevisao", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.ProfessorRedacaoRevisao", "Revisao")
                        .WithMany("CompetenciaRevisoes")
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.ProfessorRedacaoGrifo", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.ProfessorRedacaoRevisao", "Revisao")
                        .WithMany("Grifos")
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.ProfessorRedacaoRevisao", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.User", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceIEDUCA.Models.RedacaoCorrecoes", "RedacaoCorrecao")
                        .WithMany()
                        .HasForeignKey("RedacaoCorrecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("RedacaoCorrecao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoCompetencias", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.RedacaoCorrecoes", "RedacaoCorrecao")
                        .WithMany("Competencias")
                        .HasForeignKey("RedacaoCorrecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedacaoCorrecao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoCorrecoes", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.AtividadeExecucoes", "AtividadeExecucao")
                        .WithMany()
                        .HasForeignKey("AtividadeExecucaoId");

                    b.HasOne("ServiceIEDUCA.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtividadeExecucao");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoCustos", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.RedacaoCorrecoes", "Redacao")
                        .WithMany()
                        .HasForeignKey("FkRedacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Redacao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoErrosGramaticais", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.RedacaoCorrecoes", "RedacaoCorrecao")
                        .WithMany("ErrosGramaticais")
                        .HasForeignKey("RedacaoCorrecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedacaoCorrecao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoFeedbacks", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.RedacaoCorrecoes", "RedacaoCorrecao")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RedacaoCorrecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedacaoCorrecao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoPropostaIntervencao", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.RedacaoCorrecoes", "RedacaoCorrecao")
                        .WithOne("PropostaIntervencao")
                        .HasForeignKey("ServiceIEDUCA.Models.RedacaoPropostaIntervencao", "RedacaoCorrecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedacaoCorrecao");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.User", b =>
                {
                    b.HasOne("ServiceIEDUCA.Models.Escola", null)
                        .WithMany()
                        .HasForeignKey("id_Escola")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.AtividadeExecucoes", b =>
                {
                    b.Navigation("QuestaoResultados");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.Atividades", b =>
                {
                    b.Navigation("Execucoes");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.ProfessorRedacaoRevisao", b =>
                {
                    b.Navigation("CompetenciaRevisoes");

                    b.Navigation("Grifos");
                });

            modelBuilder.Entity("ServiceIEDUCA.Models.RedacaoCorrecoes", b =>
                {
                    b.Navigation("Competencias");

                    b.Navigation("ErrosGramaticais");

                    b.Navigation("Feedbacks");

                    b.Navigation("PropostaIntervencao");
                });
#pragma warning restore 612, 618
        }
    }
}
